#include<stdlib.h>
#include<stdio.h>
#include<string.h>
#include<unistd.h>
#include<fcntl.h>
#include<sys/stat.h>
#include<sys/wait.h>
#include<sys/types.h>
#include<signal.h>
#include<poll.h>
#include<sys/shm.h>
#include<sys/ipc.h>
#include<stdbool.h>
